# Generated by Django 4.1.4 on 2022-12-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_description_books_name_books_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
